#!/usr/bin/env python3

from pathlib import Path
import argparse
import pandas as pd
import matplotlib.pyplot as plt


ROOT = Path(__file__).resolve().parents[2]

DEFAULT_MATRIX = (
    ROOT
    / "results/reproducibility/recomputed_v1/tables"
    / "LAB_genus_module_matrix.csv"
)

DEFAULT_OUTDIR = (
    ROOT
    / "results/reproducibility/recomputed_v1/figures"
)

MODULE_LABELS = {
    "FM01": "FM01\nEMP glycolysis",
    "FM02": "FM02\nLactate formation",
    "FM03": "FM03\nPK/PPP-associated",
    "FM04": "FM04\nAcetate branch",
    "FM05": "FM05\nEthanol branch",
    "FM06": "FM06\nAlternative\npyruvate fates",
    "FM07": "FM07\nRedox balance",
}


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Generate the LAB genus × fermentation-module heatmap "
            "used as Figure 1 in LAB Genome Landscape."
        )
    )

    parser.add_argument(
        "--matrix",
        default=str(DEFAULT_MATRIX),
        help="Input LAB_genus_module_matrix.csv"
    )

    parser.add_argument(
        "--outdir",
        default=str(DEFAULT_OUTDIR),
        help="Directory for PNG and PDF outputs"
    )

    args = parser.parse_args()

    matrix_path = Path(args.matrix)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(matrix_path)

    modules = [
        "FM01",
        "FM02",
        "FM03",
        "FM04",
        "FM05",
        "FM06",
        "FM07",
    ]

    required = ["Genus", "N_genomes"] + modules

    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(
            f"Required columns missing from matrix: {missing}"
        )

    # Preserve the ordering generated by the analysis script:
    # genera ordered by decreasing genome count.
    data = df[modules].to_numpy(dtype=float)

    genus_labels = [
        f"{genus} (n={int(n)})"
        for genus, n in zip(df["Genus"], df["N_genomes"])
    ]

    fig, ax = plt.subplots(figsize=(11, 6.5))

    image = ax.imshow(
        data,
        aspect="auto",
        vmin=0,
        vmax=1,
    )

    ax.set_xticks(range(len(modules)))
    ax.set_xticklabels(
        [MODULE_LABELS[m] for m in modules],
        rotation=35,
        ha="right",
    )

    ax.set_yticks(range(len(df)))
    ax.set_yticklabels(genus_labels)

    ax.set_xlabel("Fermentation-associated functional module")
    ax.set_ylabel("LAB genus")

    # Numerical values displayed in each cell.
    for i in range(len(df)):
        for j in range(len(modules)):
            value = data[i, j]

            ax.text(
                j,
                i,
                f"{value:.3f}",
                ha="center",
                va="center",
                fontsize=8,
            )

    cbar = fig.colorbar(image, ax=ax)
    cbar.set_label("Mean marker prevalence")

    ax.set_title(
        "Genus-level conservation of fermentation-associated "
        "functional modules"
    )

    fig.tight_layout()

    png = outdir / "LAB_genus_module_heatmap.png"
    pdf = outdir / "LAB_genus_module_heatmap.pdf"

    fig.savefig(
        png,
        dpi=300,
        bbox_inches="tight",
    )

    fig.savefig(
        pdf,
        bbox_inches="tight",
    )

    plt.close(fig)

    print(f"WROTE: {png.relative_to(ROOT)}")
    print(f"WROTE: {pdf.relative_to(ROOT)}")

    print()
    print("FIGURE AUDIT")
    print(f"Genera:  {len(df)}")
    print(f"Modules: {len(modules)}")
    print(
        "Value range: "
        f"{data.min():.4f}–{data.max():.4f}"
    )

    print("DONE")


if __name__ == "__main__":
    main()
